---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-yaml
      - id: sort-simple-yaml
      - id: detect-private-key

  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.35.1
    hooks:
      - id: yamllint
        args: [--format, parsable, --strict]

  - repo: local
    hooks:
      - id: ansible-lint
        name: Ansible Lint
        entry: venv/bin/python3 -m ansiblelint
        language: system
        types: [yaml]
        pass_filenames: false
        always_run: true
