---
- name: Include the secrets
  ansible.builtin.include_vars:
    file: ./vars/secrets.yml
  tags: git, ssh, gpg

- name: SSH keys
  become: true
  become_user: "{{ user }}"
  no_log: true
  vars:
    ssh_key: id_ed25519
    src_ssh_key: ./files/ssh_github/{{ ssh_key }}
    dest_ssh_key: "{{ lookup('env', 'HOME') ~ '/.ssh/' ~ ssh_key }}"
  tags: ssh, git
  ansible.builtin.import_tasks: tasks/ssh.yml

- name: GPG keys
  become: true
  become_user: "{{ user }}"
  no_log: true
  vars:
    src_gpg_dir: ./files/gpg_github
    dest_gpg_dir: "{{ lookup('env', 'HOME') ~ '/.gpg_tmp' }}"
  tags: gpg, git
  ansible.builtin.import_tasks: tasks/gpg.yml

- name: Git config
  become: true
  become_user: "{{ user }}"
  tags: git
  ansible.builtin.import_tasks: tasks/git.yml

- name: ZSH config
  become: true
  become_user: "{{ user }}"
  tags: zsh
  ansible.builtin.import_tasks: tasks/zsh.yml

- name: Install Neovim
  become: true
  become_user: "{{ user }}"
  tags: neovim
  ansible.builtin.import_tasks: tasks/nvim.yml

- name: Install dotfiles
  become: true
  become_user: "{{ user }}"
  tags: dotfiles
  ansible.builtin.import_tasks: tasks/dotfiles.yml
