---
- name: SSH | Check ssh directory
  ansible.builtin.file:
    dest: "{{ dest_ssh_key | dirname }}"
    mode: "0700"
    state: directory

- name: SSH | Install the ssh keys
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode }}"
  with_items:
    - src: "{{ src_ssh_key }}"
      dest: "{{ dest_ssh_key }}"
      mode: "0600"
    - src: "{{ src_ssh_key }}.pub"
      dest: "{{ dest_ssh_key }}.pub"
      mode: "0644"

- name: SSH | Set authorized key took from file
  ansible.posix.authorized_key:
    user: "{{ user }}"
    state: present
    key: "{{ lookup('file', dest_ssh_key ~ '.pub') }}"
  with_fileglob:
    - "{{ dest_ssh_key | dirname }}/*.pub"
