---
- name: Dotfiles | Install stow
  become: true
  become_user: root
  ansible.builtin.apt:
    force_apt_get: true
    name: stow

- name: Dotfiles | Check if dotfiles exist
  ansible.builtin.stat:
    path: "{{ dotfiles.dot_dir }}"
  register: dir

- name: Dotfiles | Install dotfiles
  ansible.builtin.git:
    repo: "{{ dotfiles.repo }}"
    dest: "{{ dotfiles.dot_dir }}"
    recursive: true
    update: true
    version: master
  when: not dir.stat.exists

- name: Dotfiles | Link dotfiles
  ansible.builtin.command:
    chdir: "{{ dotfiles.dot_dir }}"
    cmd: ./install.sh
  changed_when: true
