---
- name: Dotfiles | Install stow
  become: true
  become_user: root
  ansible.builtin.apt:
    force_apt_get: true
    name: stow

- name: Dotfiles | Install dotfiles
  ansible.builtin.git:
    repo: "{{ dotfiles.repo }}"
    dest: "{{ dotfiles.dot_dir }}"
    recursive: true
    update: true
    version: master

- name: Dotfiles | Link dotfiles
  ansible.builtin.shell:
    cmd: cd "{{ dotfiles.dot_dir }}" && stow -v -R -t ~ {{ item.dir }}
  with_items:
    - dir: nvim
    - dir: zsh
    - dir: tmux
    - dir: kitty
    - dir: bin
    - dir: rustic
  changed_when: true
