---
- name: Packages | Update and upgrade packages
  tags: minimal
  ansible.builtin.apt:
    force_apt_get: true
    update_cache: true
    upgrade: true

- name: Packages | Install core packages (dkms, efibootmgr, os-prober, preload, tlp, tlp-rdw, upower, ufw, apt-transport-https, ca-certificates, gnupg-agent)
  tags: minimal
  ansible.builtin.apt:
    force_apt_get: true
    package:
      - dkms
      - efibootmgr
      - os-prober
      - preload
      - tlp
      - tlp-rdw
      - upower
      - ufw
      - apt-transport-https
      - ca-certificates
      - gnupg-agent

- name: Packages | Install build tools (build-essential, ninja-build, cmake, gettext)
  ansible.builtin.apt:
    force_apt_get: true
    package:
      - build-essential
      - ninja-build
      - cmake
      - gettext

- name: Packages | Install utility tools (curl, wget, xclip, fzf, ripgrep, ncdu, eza, bat, lm-sensors, htop, unzip, neofetch, nala, kitty, vim, tmux)
  tags: minimal
  ansible.builtin.apt:
    force_apt_get: true
    package:
      - git
      - zsh
      - curl
      - wget
      - xclip
      - fzf
      - ripgrep
      - ncdu
      - eza
      - bat
      - lm-sensors
      - htop
      - unzip
      - neofetch
      - nala
      - kitty
      - vim
      - tmux

- name: Packages | Install Python packages (python3, python3-dev, python3-pip, python3-psutil, python3-virtualenv)
  ansible.builtin.apt:
    force_apt_get: true
    package:
      - python3
      - python3-dev
      - python3-pip
      - python3-psutil
      - python3-virtualenv

- name: Packages | Install fonts (firacode)
  ansible.builtin.apt:
    force_apt_get: true
    package:
      - fonts-firacode
      # - fonts-noto
      # - fonts-noto-cjk
