---
- name: Firewall | Enable firewall
  tags: minimal
  community.general.ufw:
    state: enabled

- name: Firewall | Deny all incoming traffic
  tags: minimal
  community.general.ufw:
    default: deny
    direction: incoming

- name: Firewall | Allow all outgoing traffic
  tags: minimal
  community.general.ufw:
    default: allow
    direction: outgoing
