---
- name: Services | Disable ModemManager service
  ansible.builtin.systemd_service:
    name: ModemManager.service
    enabled: false

- name: Services | Disable NetworkManager-wait-online service
  ansible.builtin.systemd_service:
    name: NetworkManager-wait-online.service
    enabled: false

- name: Systemd | Set swappiness to 10
  ansible.posix.sysctl:
    name: vm.swappiness
    value: "10"
