---
- name: Dotfiles | Install stow
  become: true
  become_user: root
  ansible.builtin.apt:
    force_apt_get: true
    name: stow

- name: Dotfiles | Install dotfiles
  ansible.builtin.git:
    repo: "{{ dotfiles_repo }}"
    dest: "{{ lookup('env', 'HOME') }}/.dotfiles"
    recursive: true
    update: true
    version: master

- name: Dotfiles | Link dotfiles
  ansible.builtin.shell:
    cmd: cd "{{ lookup('env', 'HOME') }}/.dotfiles" && stow --adopt {{ item.dir }}
  with_items:
    - dir: nvim
    - dir: zsh
    - dir: tmux
    - dir: kitty
    - dir: bin
  changed_when: true

- name: Dotfiles | Update the remote
  ansible.builtin.shell:
    cmd: cd ~/.dotfiles && git remote remove origin && git remote add origin {{ dotfiles_repo_ssh }}
  changed_when: true
