---
- name: Packages | Update and upgrade packages
  ansible.builtin.apt:
    force_apt_get: true
    update_cache: true
    upgrade: true

- name: Packages | Install core packages
  ansible.builtin.apt:
    force_apt_get: true
    package:
      - dkms
      - efibootmgr
      - os-prober
      - preload
      - tlp
      - tlp-rdw
      - upower
      - ufw
      - apt-transport-https
      - ca-certificates
      - gnupg-agent
  tags: minimal

- name: Packages | Install build tools
  ansible.builtin.apt:
    force_apt_get: true
    package:
      - build-essential
      - ninja-build
      - cmake
      - gettext
  tags: neovim

- name: Packages | Install util tools
  ansible.builtin.apt:
    force_apt_get: true
    package:
      - curl
      - wget
      - xclip
      - findutils
      - fzf
      - lm-sensors
      - ncdu
      - gzip
      - unzip
      - grep
      - ripgrep
      - htop
      - nala
      - tree
      - exa
      - bat
      - neofetch
      - dpkg
      - git
      - zsh
      - vim
      - tmux
      - jq
      - sqlite3
      - kitty

- name: Packages | Install Python packages
  ansible.builtin.apt:
    force_apt_get: true
    package:
      - python3
      - python3-dev
      - python3-pip
      - python3-psutil
      - python3-virtualenv

- name: Packages | Install fonts
  ansible.builtin.apt:
    force_apt_get: true
    package:
      - fonts-firacode
      # - fonts-noto
      # - fonts-noto-cjk
