---
- name: Packages | Install core packages
  tags: minimal
  ansible.builtin.apt:
    force_apt_get: true
    package:
      - dkms
      - efibootmgr
      - os-prober
      - preload
      - tlp
      - tlp-rdw
      - upower
      - ufw
      - apt-transport-https
      - ca-certificates
      - gnupg-agent
      - ubuntu-restricted-extras
