---
- name: Packages | Install Python packages
  ansible.builtin.apt:
    force_apt_get: true
    package:
      - python3
      - python3-dev
      - python3-pip
      - python3-psutil
      - python3-virtualenv
