---
- name: Disable Services
  block:
    - name: Disable ModemManager service
      ansible.builtin.systemd_service:
        name: ModemManager.service
        enabled: false

    - name: Disable NetworkManager-wait-online service
      ansible.builtin.systemd_service:
        name: NetworkManager-wait-online.service
        enabled: false

- name: Setup firewall
  block:
    - name: Enable firewall
      community.general.ufw:
        state: enabled

    - name: Deny all incoming traffic
      community.general.ufw:
        default: deny
        direction: incoming

    - name: Allow all outgoing traffic
      community.general.ufw:
        default: allow
        direction: outgoing

- name: Set swappiness
  ansible.posix.sysctl:
    name: vm.swappiness
    value: "10"
    state: present
