---
- name: Setup Oh-My-Zsh
  become_user: giuseppe
  block:
    - name: Install Zsh
      ansible.builtin.apt:
        name: zsh

    - name: Set Zsh as default shell
      ansible.builtin.shell:
        cmd: chsh -s $(which zsh)
      changed_when: true

    - name: Check if Oh-My-Zsh is installed
      ansible.builtin.stat:
        path: $HOME/.oh-my-zsh
      register: oh_my_zsh_dir
      changed_when: false

    - name: Install Oh-My-Zsh
      ansible.builtin.shell:
        cmd: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
      when: not oh_my_zsh_dir.stat.exists
      changed_when: true

    - name: Install Oh-My-Zsh plugins
      block:
        - name: Zsh Syntax Highlighting
          ansible.builtin.git:
            repo: https://github.com/zsh-users/zsh-syntax-highlighting
            dest: $HOME/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting
            version: master

        - name: Zsh Syntax Autosuggestions
          ansible.builtin.git:
            repo: https://github.com/zsh-users/zsh-autosuggestions
            dest: $HOME/.oh-my-zsh/custom/plugins/zsh-autosuggestions
            version: master
