---
- name: Packages | Apt | Add cryptomator ppa repository
  ansible.builtin.apt_repository:
    repo: ppa:sebastian-stenzel/cryptomator

- name: Packages | Apt | Install cryptomator
  ansible.builtin.apt:
    force_apt_get: true
    update_cache: true
    name: cryptomator
