---
- name: Packages | Apt | Install megasync
  ansible.builtin.apt:
    force_apt_get: true
    update_cache: true
    deb: https://mega.nz/linux/repo/xUbuntu_24.04/amd64/megasync-xUbuntu_24.04_amd64.deb

- name: Packages | Apt | Install megasync nautilus
  ansible.builtin.apt:
    force_apt_get: true
    deb: https://mega.nz/linux/repo/xUbuntu_24.04/amd64/nautilus-megasync-xUbuntu_24.04_amd64.deb
