---
- name: Packages | Apt | Install Visual Studio Code
  tags: vscode
  ansible.builtin.apt:
    force_apt_get: true
    update_cache: true
    deb: https://code.visualstudio.com/sha/download?build=stable&os=linux-deb-x64
