---
- name: Include gpg variables
  ansible.builtin.include_vars: vars/gpg_vars.yml

- name: Include vault gpg variables
  ansible.builtin.include_vars: vars/gpg_vault.yml

- name: GPG | Create the temp directory for gpg keys
  ansible.builtin.file:
    dest: "{{ gpg_dest_dir }}"
    mode: "0700"
    state: directory

- name: GPG | Copy temporary gpg keys
  no_log: true
  ansible.builtin.copy:
    src: "{{ gpg_src_dir ~ '/' ~ item.src }}"
    dest: "{{ gpg_dest_dir ~ '/' ~ item.dest }}"
    mode: "{{ item.mode }}"
  with_items:
    - src: private.asc
      dest: private.asc
      mode: "0600"
    - src: public.asc
      dest: public.asc
      mode: "0644"

- name: GPG | Import the gpg private key
  no_log: true
  ansible.builtin.shell:
    cmd: |
      set -o pipefail
      echo {{ gpg_passphrase }} | gpg --batch --yes --passphrase-fd 0 --import {{ gpg_dest_dir }}/private.asc
    executable: /bin/bash
  changed_when: true

- name: GPG | Import the gpg public key
  no_log: true
  ansible.builtin.shell:
    cmd: |
      set -o pipefail
      echo {{ gpg_passphrase }} | gpg --batch --yes --passphrase-fd 0 --import {{ gpg_dest_dir }}/public.asc
    executable: /bin/bash
  changed_when: true

- name: GPG | Remove the temporary gpg keys
  ansible.builtin.file:
    path: "{{ gpg_dest_dir }}"
    state: absent
  changed_when: true

- name: GPG | Fix the trust level
  no_log: true
  ansible.builtin.shell:
    cmd: |
      set -o pipefail
      echo -e "5\ny\nsave\n" | gpg --batch --command-fd 0 --edit-key {{ gpg_key_id }} trust quit >/dev/null 2>&1
    executable: /bin/bash
  changed_when: true
