---
- name: Firewall | Enable firewall
  become: true
  community.general.ufw:
    state: enabled

- name: Firewall | Deny all incoming traffic
  become: true
  community.general.ufw:
    default: deny
    direction: incoming

- name: Firewall | Allow all outgoing traffic
  become: true
  community.general.ufw:
    default: allow
    direction: outgoing
