---
- name: Laptop Ubuntu Setup (Minimal)
  hosts: localhost
  connection: local
  gather_facts: false

  pre_tasks:
    - name: Register Current User
      ansible.builtin.import_tasks: pre_tasks/register_user.yml

  tasks:
    - name: Include roles
      ansible.builtin.include_role:
        name: "{{ roles_item }}"
      loop_control:
        loop_var: roles_item
      with_items:
        - name: packages
        - name: ufw
        - name: ssh
        - name: gpg
        - name: git
        - name: zsh
        - name: dotfiles
