---
- name: Rust | Download Script
  ansible.builtin.get_url:
    url: https://sh.rustup.rs
    dest: /tmp/sh.rustup.rs
    mode: "0755"

- name: Rust | Install
  ansible.builtin.shell: >
    /tmp/sh.rustup.rs -y
  args:
    creates: "{{ lookup('env', 'HOME') }}/.cargo/bin/rustup"
